export const notesTypes = {
  NOTES_ADD_NOTE: '[NOTES] ADD NEW',
  NOTES_SET_ACTIVE: '[NOTES] SET ACTIVE',
  NOTES_LOAD: '[NOTES] LOAD',
  NOTES_UPDATE: '[NOTES] UPDATE NOTE',
  NOTES_FILE_URL: '[NOTES] UPDATE IMAGE URL',
  NOTES_REMOVE_NOTE: '[NOTES] REMOVE NEW',
  NOTES_LOGOUT_CLEAN: '[NOTES] LOGOUT CLEAN',
};
